### ISSUE TITLE
Styling required on multiple pages

### ISSUE THREAD

**Issue by pranshu-s18** [4molybdenum2/xylo#12]
1. myposts division on the dashboard page
2. Sign-Up button on the login page
3. Lesser spacing between Comment and person name

**Comment by 4molybdenum2** [comment]
we should also make a page where we can access all stories

**Comment by pranshu-s18** [comment]
Sure. Will do it in the evening.

**Comment by pranshu-s18** [comment]
All stories page has been created. Styling required.

**Comment by pranshu-s18** [comment]
1. myposts division on the dashboard page
2. Sign-Up button on the login page
3. Lesser spacing between Comment and person name

**Comment by 4molybdenum2** [comment]
keeping the next and previous on stories/id page is ok...but if no next story exists then clicking the button leads to an error 404 page

**Comment by 4molybdenum2** [comment]
pls add required condition
