### ISSUE TITLE
Setup Repo

### ISSUE THREAD

**Issue by 4molybdenum2** [4molybdenum2/xylo#32]
The website is down currently. There is an empty db config file under db folder. Setup a new Heroku server with MySQL support and test whether the website is working properly or not. You can also test it locally. Also plus points for upgrading all the packages to their latest versions.

**Comment by sohan2410** [comment]
I would like to work on this issue

**Comment by sohan2410** [comment]
@4molybdenum2 I was trying to add-on `ClearDB MySQL` in heroku app but it was asking for credit card information. Can we try for some other alternative??

**Comment by 4molybdenum2** [comment]
Actually this issue was created just so that you can setup the current repo in your local repo to allow working on other stuff. Ig, set up locally now and we will figure something out about the website later
@sohan2410

**Comment by sohan2410** [comment]
So that means connecting to local MySql database?
