### ISSUE TITLE
Site Design

### ISSUE THREAD

**Issue by 4molybdenum2** [4molybdenum2/xylo#33]
Iterate over the homepage design after setting up SQL connection locally. Then post relevant screenshots of so.
Important points to reconsider:
- [x] Remove the social icons on homepage on the right side of the screen
- [x] Remove all animations (we will later decide whether it is necessary)
- [x] Select better fonts for homepage
- [x] Make the site more accessible (you can check out about accessibility at https://www.w3.org/standards/webdesign/accessibility)

**Comment by 4molybdenum2** [comment]
Go ahead @arushi2715

**Comment by arushi2715** [comment]
Hey @4molybdenum2, after connecting it to database when I'm running it locally, it is showing error.
Can you tell how to fix this?

**Comment by 4molybdenum2** [comment]
Can you send the logs ..? @arushi2715

**Comment by 4molybdenum2** [comment]
Can you link the PR?
